# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160102_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tz',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
