# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userprofile_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tz',
            field=models.CharField(blank=True, default='America/New_York', max_length=100),
        ),
    ]
