# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160107_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='readers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
