# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160107_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
    ]
