# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_userprofile_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livetvusername', models.CharField(max_length=40)),
                ('minutes', models.FloatField()),
                ('viewers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes_leaders', models.ManyToManyField(related_name='minutes_leaders', to='app.Leader')),
                ('viewers_leaders', models.ManyToManyField(related_name='viewers_leaders', to='app.Leader')),
            ],
        ),
    ]
