# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_leader_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
