# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160108_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='minutes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='viewers',
            field=models.IntegerField(null=True),
        ),
    ]
