# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160108_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
    ]
