# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20160108_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLeaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('monthly', models.BooleanField(default=False)),
                ('minutes_leaders', models.ManyToManyField(related_name='minutes_leaders', to='app.Leader')),
                ('viewers_leaders', models.ManyToManyField(related_name='viewers_leaders', to='app.Leader')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='minutes_leaders',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='viewers_leaders',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.AlterUniqueTogether(
            name='dailyleaderboard',
            unique_together=set([('date', 'monthly')]),
        ),
    ]
