# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160108_1726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyleaderboard',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dailyleaderboard',
            name='monthly',
        ),
    ]
