# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160108_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyleaderboard',
            options={'ordering': ['-date']},
        ),
    ]
