# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160109_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
