# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_userprofile_oauth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaccesstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verified',
        ),
        migrations.DeleteModel(
            name='ApiAccessToken',
        ),
    ]
