# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_apiaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth_refresh_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
