# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_userprofile_oauth_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiaccesstoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApiAccessToken',
        ),
    ]
